services:
  - type: web
    name: diagramiq-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: 5000

